INSERT or IGNORE into ingredient(name, classification) values('milk', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('almond milk', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('butter', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('buttermilk', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('condensed milk', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('custard', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('evaporated milk', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('half & half', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('paneer', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('pudding', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('sour cream', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('whipped cream', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('yogurt', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('cottage cheese', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('ricotta cheese', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('heavy cream', 'dairy');
INSERT or IGNORE into ingredient(name, classification) values('cream cheese', 'dairy');

INSERT or IGNORE into ingredient(name, classification) values('apple', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('banana', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('lemon', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('lime', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('garlic', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('avacado', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('kiwi', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('tomatoe', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('orange', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('cucumber', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('potato', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('red bell pepper', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('green bell pepper', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('strawberry', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('onion', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('carrot', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('lettuce', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('raspberry', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('zucchini', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('grape', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('celery', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('pear', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('broccoli', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('jalapeno', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('asparagus', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('blueberry', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('grapefruit', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('yellow bell pepper', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('brussel sprout', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('canteloupe', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('mushroom', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('blackberry', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('spinach', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('cauliflower', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('cilantro', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('pineapple', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('cabbage', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('peach', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('mango', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('kale', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('green bean', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('ginger', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('shallots', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('radish', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('parsley', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('corn', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('plum', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('spaghetti squash', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('acorn squash', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('butternut squash', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('mandarin', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('nectarine', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('eggplant', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('parsnip', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('turnip', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('watermelon', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('leek', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('plum', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('bok choy', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('plantain', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('honeydew', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('collard greens', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('artichoke', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('flennel', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('chive', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('okra', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('rutabaga', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('bean sprouts', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('basil', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('kohlrabi', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('chives', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('chard', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('oregano', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('alfalfa', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('brocoletti', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('daikon', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('papaya', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('beet', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('soybean', 'produce');
INSERT or IGNORE into ingredient(name, classification) values('arugala', 'produce');

INSERT or IGNORE into ingredient(name, classification) values('chicken', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('turkey', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('pork', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('ham', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('tofu', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('egg', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('beef', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('ground beef', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('lamb', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('fish', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('pepperoni', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('sausage', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('salmon', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('talapia', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('salami', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('wagyu', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('duck', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('goose', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('tuna', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('bison', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('crab', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('pollock', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('shrimp', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('deer', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('alligator', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('rabbit', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('goat', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('pheasant', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('anchovy', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('liver', 'meat');
INSERT or IGNORE into ingredient(name, classification) values('quail', 'meat');

INSERT or IGNORE into ingredient(name, classification) values('pasta', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('rice', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('quinoa', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('barley', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('buckwheat', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('millet', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('oat', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('maize', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('sorghum', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('flour', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('rye', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('lentil', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('amaranth', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('farro', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('wheat', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('freekeh', 'grain');
INSERT or IGNORE into ingredient(name, classification) values('teff', 'grain');

INSERT or IGNORE into ingredient(name, classification) values('cinnamon', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('adobo seasoning', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('chili powder', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('allspice', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('cumin', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('paprika', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('basil', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('nutmeg', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('oregano', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('turmeric', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('clove', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('rosemary', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('thyme', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('sage', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('cayenne pepper', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('curry powder', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('garlic powder', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('saffron', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('mace', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('tarragon', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('salt', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('pepper', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('coriander', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('anise', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('celery salt', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('cardamon', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('fenugreek', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('dill', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('parsley', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('sumac', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('pumpkin spice', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('mustard', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('marjoram', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('vanilla', 'spice');
INSERT or IGNORE into ingredient(name, classification) values('chervil', 'spice');